### ISSUE TITLE
CI builds

### ISSUE THREAD

**Issue by paulvi** [kingargyle/andmore#37]
while manually building is nice,  
it would save time to many would-be-users if there was automatic build for every commit and updating public p2 repository

@pascalleclercq has been helping to @angelozerr with AngularJS-Eclipse and Tern-IDE

**Comment by dschaefer** [comment]
We should get a HIPP instance at Eclipse (like http://hudson.eclipse.org/cdt) so we can set up a number of builds as needed. And we should get space on http://downloads.eclipse.org/tools/admore which I don't see provisioned yet.

**Comment by kingargyle** [comment]
Yeah.  @dschaefer open a bug for the Web Masters at eclipse on bugzilla.  We also need to start looking at a Gerritt instance.

Also I think we need to start setting up the Bugzilla for the Andmore project at Eclipse.  Eventually this issue tracker will go away once we turn the repo over to Eclipse.

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore

**Comment by dschaefer** [comment]
Done: https://bugs.eclipse.org/bugs/show_bug.cgi?id=456821

I guess, though, we can't really use it until the code has passed Eclipse IP inspection, no?

**Comment by kingargyle** [comment]
We'll probably need to discuss with the foundation on that.  We are going through Parallel IP, so there is some leeway given to new projects that use parallel ip.  Probably a good idea to start a discussion in the andmore-dev mailing list as well.

https://dev.eclipse.org/mailman/listinfo/andmore-dev

**Comment by paulvi** [comment]
IMHO, GitHub discussions are better experience.  
Especially when discussion happens in real time. 

What is guessed time frame for passing IP review ?

**Comment by kingargyle** [comment]
I'm almost complete with the dependency list, and will get the main code in place for IP review after I finish finding the dependencies that the former motodev studio plugins used.   I'm hoping to submit it eclipse for review, and parallel IP process by the end of the week.

Once this repo is turned over to eclipse, then the Github issues will be going away unfortunately.  We'll still have the repo on GithHub, but the issue tracker will be closed as eclipse wants us to use their bug tracking system.   If pull requests aren't working after this, we'll be using Gerrit at eclipse which serves a similar purpose as pull requests so can keep conversations there.

**Comment by paulvi** [comment]
>  If pull requests aren't working after this,

They will work even with disabled/hidden issues.

**Comment by kingargyle** [comment]
Cool, thanks for the info on pull requests.  Yeah, I'll refork the repo once this one is moved to eclipse/andmore.  So it will be here just my personal copy.

**Comment by paulvi** [comment]
BTW, once you re-fork (or push to new) the issue will start again from 1.
So hiding issue in new repository and switching to Bugzilla will solve "number one in new or old repo?" problem.

**Comment by kingargyle** [comment]
All commits will be squashed into one commit, per the Eclipse requirements.  So existing numbers will be lost regardless, and bugzilla numbers will be all that is left.

Right now this issue tracker is primarly for the leg work to get things going.  We do have bugzilla running now.

**Comment by kingargyle** [comment]
We'll be transfering owner ship to eclipse starting today.  Eventually this issue tracker will be closed.  Please open bugs at  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=andmore.
